// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": process.env.VUE_APP_AWS_REGION,
    "aws_appsync_graphqlEndpoint": process.env.VUE_APP_AWS_API_ENDPOINT,
    "aws_appsync_region": process.env.VUE_APP_AWS_REGION,
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": process.env.VUE_APP_AWS_APPSYNC_API_KEY
}


export default awsmobile;
